FROM python:3.12

WORKDIR /app

COPY . .

RUN chmod +x wait-for-it.sh
RUN pip install --no-cache-dir -r requirement.txt

EXPOSE 8000:8000


CMD ["./wait-for-it.sh", "db:3306", "--", "./wait-for-it.sh", "minio:9000", "--", "sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]