from .signup_service import SignupService
from .calculator_service import CalculatorService
from .education_evaluator_service import EducationEvaluationService
from .ocr_service import OCRService
from .login_service import LoginService
from .grade_verify_service import GradeVerificationService
from .fill_curriculum_checking_service import FillCurriculumCheckingService
from .view_pending_forms_service import ViewPendingFormsService