# Generated by Django 5.1.5 on 2025-02-17 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDetail',
            fields=[
                ('credit_details_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('credit_status', models.IntegerField(choices=[(1, 'Complete'), (0, 'Incomplete')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('form_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='draft', max_length=10)),
                ('form_type', models.CharField(choices=[('credit check', 'Check'), ('graduated verify', 'Verify')], max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryDetails',
            fields=[
                ('subcategory_detail_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('acquired_credit', models.IntegerField()),
                ('credit_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.creditdetail')),
                ('subcateory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('verification_result_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result_status', models.IntegerField(choices=[(1, 'Pass'), (0, 'Not Pass')], default=0)),
                ('activity_status', models.IntegerField(choices=[(1, 'Pass'), (0, 'Not Pass')], default=0)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.form')),
            ],
        ),
        migrations.AddField(
            model_name='creditdetail',
            name='verification_result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.verificationresult'),
        ),
    ]
