# Generated by Django 5.1.5 on 2025-02-23 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('otp_verification_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('reference_otp', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('form_status', models.CharField(choices=[('ready to calc', 'Ready To Calc'), ('draft', 'Draft'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('form_type', models.CharField(choices=[('credit check', 'Credit Check'), ('graduation check', 'Graduation Check')], default='graduation check', max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
