
# Generated by Django 5.1.5 on 2025-02-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_curriculum_id_category_curriculum_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.IntegerField(choices=[(0, 'Summer'), (1, 'First'), (2, 'Second')]),
        ),
    ]
