# Generated by Django 5.1.5 on 2025-03-02 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_enrollment_grade_alter_enrollment_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('otp_verification_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('reference_otp', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='form_status',
            field=models.CharField(choices=[('ready to calc', 'Ready To Calc'), ('draft', 'Draft'), ('pending', 'Pending'), ('verified', 'Verified')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_type',
            field=models.CharField(choices=[('credit check', 'Credit Check'), ('graduation check', 'Graduation Check')], default='graduation check', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
