# Generated by Django 5.1.5 on 2025-03-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_verificationresult_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorydetails',
            name='category_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
    ]
