# Generated by Django 5.1.5 on 2025-03-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subcategorydetails_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorydetails',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='subcategorydetails',
            name='subcateory_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
