# Generated by Django 5.1.5 on 2025-03-12 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_subcategorydetails_category_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotPassCourse',
            fields=[
                ('not_pass_course_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('credit_detail_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.creditdetail')),
                ('subcategory_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
        ),
    ]
