# Generated by Django 5.1.5 on 2025-03-12 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_notpasscourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notpasscourse',
            name='subcategory_fk',
        ),
        migrations.AddField(
            model_name='notpasscourse',
            name='enrollment_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.enrollment'),
            preserve_default=False,
        ),
    ]
