# Generated by Django 5.1.5 on 2025-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_credit_details_fk_subcategorydetails_credit_detail_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorydetails',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
    ]
