from .signup_view import signup_view
from .otp_verify_view import otp_verify_view
from .user_signup_view import user_signup_view
from .login_view import login_view
from .grade_verify_view import GradeVerifyView
from .upload_view import FileUploadView
from .calculate_view import CalculateView
from .fill_curriculum_checking_view import fillCurriculumCheckingView 
from .pending_forms_view import pending_forms_view
from .file_attach_list_view import FileAttachListView